### ISSUE TITLE
BlogRoll: Begrense antall innlegg på hovedsiden

### ISSUE THREAD

**Issue by martcl** [nadderud/mbube#10]
### For mange innlegg 
Akkurat nå er det ingen begrensning på hvor mange blogginnlegg som kan vises på hovedsiden. Det burde bli satt en grense på 4 eller 6.

**Comment by mgrim** [comment]
Enig. Men bør filteret være på antall eller dato?

Jeg tenker det kan være en ide å vise innlegg fra de siste to-tre månedene på forsiden, og så en egen side for eldre innlegg. Da er forsiden alltid rimelig oppdatert, og den eneste grunnen til å bla i gamle innlegg er at du leter etter gammel informasjon.

En enda mer fiffig løsning er å sette en utløpsdato på innlegg, når de ikke lenger er aktuelle, og bare vise aktuelle innlegg på forsiden.

Uansett må vi ha en visning for "non-ideal state", når det ikke er noen aktuelle saker å vise.

**Comment by martcl** [comment]
Jeg likte ideen med å sortere med utgangspunktet i en type utløpsdato! Da må vi legge til en ny dato variabel i hver _frontmatter_ for innleggene. Kanskje burde denne datoen være starten på arrangementet. Fordi da kan vi i fremtiden lage en "nedtelling" til arrangementet begynner. Så kan vi heller la det gå noen dager, før vi fjerner innlegget.

Når vi begrenser antall innlegg, burde vi samtidig få opp en arkivside. Slik at informasjonen er tilgjengelig selv etter innleggs-kuttet. Jeg tenker at arkivet burde være ganske lik designet til blogRoll, men mindre. Slik at det er plass til 3 innlegg i bredden.

Jeg kan starte å lage en arkiv side, fordi jeg er ikke så god på Netlify cms. Hvis du har mulighet kan du se på en passende filtereringsmetode.
