### ISSUE TITLE
App: Rebuild site

### ISSUE THREAD

**Issue by martcl** [nadderud/mbube#14]
Jeg foreslår en funksjon for å bygge siden på nytt, fra selve nettsiden. Slik kan Troppsleder og andre enhetsledere oppdatere programmet i `/program/`, uten å kontakte hjelp. 

Hvis en slik funksjonalitet er mulig å implementere, hadde den hjulpet med å gi ut informasjon kjappere. Fordi en slipper å gå gjennom et mellomledd.

**Comment by mgrim** [comment]
Det er en god ide - og det finnes flere muligheter:

* Vi kan lage en knapp i CMS-et som trigger rebuild.
* Vi kan lage en bot (e-post, messenger, e.l.) som kan få beskjed om å bygge siden på nytt.
* Vi kan sette opp en automatisk rebuild etter et gitt intervall (f.eks. en gang pr. dag).
* Vi kan bruke webhooks (https://developers.google.com/calendar/v3/push) for å oppdage når terminlista bør oppdateres.

Utfordringen med de to siste blir å holde seg innenfor gratiskvota til Netlify på 300 build minutes/month (https://www.netlify.com/pricing/). Ev. vurdere en annen host.
