### ISSUE TITLE
Pakkeliste og reglement

### ISSUE THREAD

**Issue by martcl** [nadderud/mbube#16]
Legge til sider med pakkeliste og reglement for leir, slik at det er mulig å lenke til dem i innleggene.

**Comment by mgrim** [comment]
Bør dette bli en "prosjekt-side", hvor vi kan samle relevant informasjon om leir?
F.eks. kan www.nadderud.no/leir alltid være linken til førstkommende leir...

Dette er jo tross alt en ganske regelmessig aktivitet.

**Comment by martcl** [comment]
Enig!
