### ISSUE TITLE
Flytte overskrift i innlegg  

### ISSUE THREAD

**Issue by martcl** [nadderud/mbube#7]
### Flytte overskrift?
Jeg synes at overskriften på arrangementene dekker for mye av bilde. Noen ganger er tittelen på innleggene veldig lange, som fører til at store deler av bilde blir dekket til. Mobiler er spesielt utsatt for dette. 
Slik jeg ser det, er det veldig dumt at mobil-brukerene bruker tid/kraft på å rendre bilde hvis de ikke ser det. På PC er dette ikke et stort problem, men hvis vi flytter overskriften blir det endret på begge plattformer uansett.

Hva er dine tanker?

![Skjermbilde 2019-12-20 kl  21 28 07](https://user-images.githubusercontent.com/26656069/71291578-5c998e80-2373-11ea-8ae1-7330d29d0df0.png)

![Skjermbilde 2019-12-20 kl  21 38 30](https://user-images.githubusercontent.com/26656069/71293608-42ad7b00-2376-11ea-9b75-ed20b83fd2bb.png)

**Comment by mgrim** [comment]
Støttes! I så fall bør også høyden på bildet reduseres i mobilvisningen (det tar jo nå mer enn halve høyden på viewport).

**Comment by martcl** [comment]
Enig! Jeg pusher noe i løpet av de neste dagene

**Comment by mgrim** [comment]
Løst av #9
